#!/usr/bin/env node
// Real WebSocket/PCM/recording benchmark. No IAM or voice-provider network calls.
import assert from 'node:assert/strict';
import {mkdtemp, writeFile, readFile, rm, stat} from 'node:fs/promises';
import {tmpdir, cpus, platform, arch} from 'node:os';
import {join, resolve} from 'node:path';
import {spawn, execFile} from 'node:child_process';
import {once} from 'node:events';
import {parseArgs, promisify} from 'node:util';
import {randomBytes, randomUUID} from 'node:crypto';
import {createServer} from 'node:net';

const {values:args}=parseArgs({options:{calls:{type:'string',default:'15'},seconds:{type:'string',default:'30'},url:{type:'string'},'secrets-file':{type:'string'},binary:{type:'string',default:'target/debug/ring-server'},port:{type:'string',default:'0'},pid:{type:'string'},report:{type:'string'},'prepare-fixtures':{type:'string'},help:{type:'boolean'}}});
if(args.help){console.log('node scripts/load-test.mjs [--calls 15] [--seconds 30] [--binary target/release/ring-server] [--report result.json]\nRemote: --url wss://HOST/ws --secrets-file FILE [--pid LOCAL_SERVER_PID]\nPrepare protected remote test inputs: --prepare-fixtures FILE (also writes FILE.tokens.private.json).');process.exit(0);}
const count=Number(args.calls),seconds=Number(args.seconds),frames=Math.round(seconds*50);
assert(Number.isInteger(count)&&count>=1&&count<=100,'calls must be 1–100');
assert(Number.isFinite(seconds)&&seconds>=1&&seconds<=300,'seconds must be 1–300');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const fixture={test_app_secret:randomBytes(32).toString('hex'),org_id:'ring-load',identities:{}};
for(let n=0;n<count*2;n++)fixture.identities[randomBytes(24).toString('hex')]={actor:`c:load${n}`,org_id:fixture.org_id,display_name:`Load ${n}`,admin:false};
if(args['prepare-fixtures']){const path=resolve(args['prepare-fixtures']);await writeFile(path,JSON.stringify(fixture,null,2),{mode:0o600,flag:'wx'});await writeFile(`${path}.tokens.private.json`,JSON.stringify(fixture.identities),{mode:0o600,flag:'wx'});console.log(`Prepared ${count*2} isolated test identities in ${path} and ${path}.tokens.private.json`);process.exit(0);}
let directory,server,output='',sampling,pid,startedAt=0;
const clients=[],calls=[],resources=[],errors=[],latencies=[],lateness=[];
let sentFrames=0,receivedFrames=0,sentWireBytes=0,receivedWireBytes=0;
let settings=fixture,url=args.url;
if(url){assert(args['secrets-file'],'Remote mode requires --secrets-file');const info=await stat(args['secrets-file']);assert((info.mode&0o077)===0,'Secrets file must be private (chmod 600)');settings=JSON.parse(await readFile(args['secrets-file'],'utf8'));const parsed=new URL(url);assert(['ws:','wss:'].includes(parsed.protocol)&&!parsed.username&&!parsed.password,'Invalid WebSocket URL');assert(parsed.protocol==='wss:'||['127.0.0.1','localhost','[::1]'].includes(parsed.hostname),'Remote benchmark requires TLS');}
assert(typeof settings.test_app_secret==='string'&&settings.test_app_secret.length>=24,'Test app secret required');
const identities=Object.entries(settings.identities||{}).filter(([,v])=>v.org_id===settings.org_id&&v.actor?.startsWith('c:')).slice(0,count*2);
assert.equal(identities.length,count*2,'Need two carbon test identities per call');

function pcm(lane,tag,seq){const bytes=Buffer.alloc(960);for(let i=lane;i<480;i+=2)bytes.writeInt16LE(i===lane?seq+1:i===lane+2?tag:1000+(seq+i+tag)%2000,i*2);return bytes;}
function quantile(v,p){if(!v.length)return null;const a=[...v].sort((x,y)=>x-y);return Math.round(a[Math.floor((a.length-1)*p)]*100)/100;}
function cpuSeconds(value){return value.split(':').reverse().reduce((n,v,i)=>n+Number(v)*60**i,0);}
async function sample(){if(!pid)return;try{const {stdout}=await promisify(execFile)('ps',['-p',String(pid),'-o','rss=','-o','time=']);const [rss,time]=stdout.trim().split(/\s+/);if(rss&&time)resources.push({at:performance.now(),rss_kib:Number(rss),cpu_seconds:cpuSeconds(time)});}catch{}}
function issue(message){if(errors.length<100)errors.push(message);}
class Client{
 constructor(socket,index){this.socket=socket;this.index=index;this.lane=index%2;this.tag=index+1;this.pending=new Map();this.assets=new Map();this.sent=new Map();this.received=new Set();this.lastOutput=-1;socket.addEventListener('message',ev=>{receivedWireBytes+=Buffer.byteLength(ev.data);let v;try{v=JSON.parse(ev.data);}catch{issue('Server returned non-JSON data');return;}if(v.id&&this.pending.has(v.id)){const p=this.pending.get(v.id);clearTimeout(p.timer);this.pending.delete(v.id);v.ok?p.resolve(v.result):p.reject(new Error(`${p.method}: ${v.error?.code||'failed'}`));return;}if(v.type==='media.audio')this.audio(v.data);else if(v.type==='assets.chunk'){const a=this.assets.get(v.data.transfer_id)||[];a.push(v.data);this.assets.set(v.data.transfer_id,a);}else if(v.type==='protocol.ping')this.socket.send(JSON.stringify({type:'protocol.pong',data:{}}));else if(v.error)issue(`Stream ${this.index}: ${v.error.code}`);});}
 request(method,params={}){return new Promise((resolve,reject)=>{const id=randomUUID(),timer=setTimeout(()=>{this.pending.delete(id);reject(new Error(`Timeout: ${method}`));},15000);this.pending.set(id,{resolve,reject,timer,method});this.socket.send(JSON.stringify({id,method,params}));});}
 audio(data){if(!this.peer)return;const bytes=Buffer.from(data.audio_base64,'base64');if(bytes.length!==960){issue(`Stream ${this.index}: wrong PCM frame length`);return;}if(this.lastOutput>=0&&data.seq!==this.lastOutput+1)issue(`Stream ${this.index}: output sequence gap`);this.lastOutput=data.seq;const marker=bytes.readInt16LE(this.peer.lane*2);if(marker===0){if(bytes.some(v=>v!==0))issue(`Stream ${this.index}: invalid silence/self-mix`);return;}const seq=marker-1;if(seq<0||seq>=frames||!bytes.equals(pcm(this.peer.lane,this.peer.tag,seq))){issue(`Stream ${this.index}: corrupted audio or cross-call leakage`);return;}if(this.received.has(seq)){issue(`Stream ${this.index}: duplicate frame ${seq}`);return;}this.received.add(seq);receivedFrames++;const sent=this.peer.sent.get(seq);if(sent===undefined)issue(`Stream ${this.index}: unexpected frame ${seq}`);else latencies.push(performance.now()-sent);}
 send(seq){const packet=JSON.stringify({type:'media.audio',data:{stream_id:this.stream.stream_id,seq,offset_ms:seq*20,audio_base64:pcm(this.lane,this.tag,seq).toString('base64')}});this.sent.set(seq,performance.now());this.socket.send(packet);sentWireBytes+=Buffer.byteLength(packet);sentFrames++;}
 async asset(id){const meta=await this.request('assets.get',{asset_id:id});assert.equal(meta.complete,true,'Recording asset incomplete');for(let n=0;n<300;n++){const chunks=this.assets.get(meta.transfer_id);if(chunks?.some(c=>c.final)){chunks.sort((a,b)=>a.seq-b.seq);chunks.forEach((v,i)=>assert.equal(v.seq,i,'Missing asset chunk'));const bytes=Buffer.concat(chunks.map(c=>Buffer.from(c.data_base64,'base64')));assert.equal(bytes.length,meta.size_bytes,'Recording transfer truncated');this.assets.delete(meta.transfer_id);return bytes;}await delay(20);}throw new Error('Recording transfer timed out');}
 close(){this.socket.close();for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(new Error('Benchmark closed'));}this.pending.clear();}
}
async function connect(index){const socket=new WebSocket(url);await new Promise((res,rej)=>{socket.addEventListener('open',res,{once:true});socket.addEventListener('error',()=>rej(new Error('WebSocket connection failed')),{once:true});});const c=new Client(socket,index);clients.push(c);await c.request('protocol.hello',{versions:[1],realm:'test',org_id:settings.org_id,test_app_secret:settings.test_app_secret,client:{name:'ring-load-test',version:'0.1.0'}});c.session=await c.request('auth.login',{token:identities[index][0]});return c;}
async function stop(){for(const c of clients)c.close();if(server?.pid&&server.exitCode===null){const closed=once(server,'exit');const kill=setTimeout(()=>server.kill('SIGKILL'),5000);kill.unref();server.kill('SIGINT');await closed;clearTimeout(kill);}if(sampling)clearInterval(sampling);if(directory)await rm(directory,{recursive:true,force:true});}
const recordings=[];
let elapsed=0;
try{
 if(!url){directory=await mkdtemp(join(tmpdir(),'ring-load-'));await writeFile(join(directory,'tokens.json'),JSON.stringify(settings.identities),{mode:0o600});const probe=createServer();await new Promise(r=>probe.listen(Number(args.port),'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));url=`ws://127.0.0.1:${port}/ws`;server=spawn(resolve(args.binary),[],{env:{...process.env,RING_BIND:`127.0.0.1:${port}`,RING_DATA_DIR:directory,RING_ENV:'test',RUST_LOG:'ring_server=info',RING_TEST_APP_SECRET:settings.test_app_secret,RING_TEST_TOKENS_FILE:join(directory,'tokens.json'),RING_DISABLE_PROVIDERS:'1',RING_TELEMETRY_ENABLED:'false'},stdio:['ignore','pipe','pipe']});server.stdout.on('data',c=>output=(output+c).slice(-4000));server.stderr.on('data',c=>output=(output+c).slice(-4000));server.on('error',()=>issue('Server executable could not start'));for(let n=0;n<200;n++){if(server.exitCode!==null)throw new Error('Owned server exited before readiness');try{if(output.includes('Ring server listening')&&(await fetch(`http://127.0.0.1:${port}/health`)).ok)break;}catch{}if(n===199)throw new Error('Server did not become healthy');await delay(50);}pid=server.pid;}else if(args.pid)pid=Number(args.pid);
 // Setup is sequential to avoid benchmarking database bootstrap as media latency.
 for(let n=0;n<count;n++){const a=await connect(n*2),b=await connect(n*2+1);a.peer=b;b.peer=a;const call=await a.request('calls.init',{target:identities[n*2+1][1].actor});const entry={a,b,ringid:call.ringid};calls.push(entry);await b.request('calls.accept',{ringid:call.ringid});for(const c of [a,b])c.stream=await c.request('media.attach',{ringid:call.ringid,device_id:c.session.device_id,purpose:'call'});}
 await sample();sampling=setInterval(()=>void sample(),1000);startedAt=performance.now();
 let target=startedAt;for(let seq=0;seq<frames;seq++){await delay(Math.max(0,target-performance.now()));const actual=performance.now(),late=Math.max(0,actual-target);lateness.push(late);for(const c of clients)c.send(seq);target=late>20?actual+20:target+20;}
 const expected=count*2*frames;
 for(let n=0;n<500&&receivedFrames<expected;n++)await delay(20);
 elapsed=(performance.now()-startedAt)/1000;await sample();clearInterval(sampling);sampling=null;
 for(const c of clients)if(c.received.size!==frames)issue(`Stream ${c.index}: received ${c.received.size}/${frames} input frames`);
 for(const call of calls){await call.a.request('calls.cut',{ringid:call.ringid});assert.equal((await call.b.request('calls.get',{ringid:call.ringid})).state,'ended','Call did not end');let record;for(let n=0;n<100;n++){record=await call.b.request('recordings.get',{ringid:call.ringid});if(record.status==='ready'||record.status==='failed')break;await delay(30);}const summary={ringid:call.ringid,status:record.status,coverage:record.coverage,missing_intervals:record.missing_intervals||[],duration_ms:record.duration_ms};recordings.push(summary);if(record.status!=='ready'||record.coverage!=='full'||summary.missing_intervals.length)issue(`Recording ${call.ringid}: ${record.status}/${record.coverage}, ${summary.missing_intervals.length} missing intervals`);if(!record.audio_asset_id)continue;try{const bytes=await call.a.asset(record.audio_asset_id);assert.equal(bytes.subarray(0,4).toString(),'RIFF');assert.equal(bytes.subarray(8,12).toString(),'WAVE');assert.equal(bytes.readUInt32LE(24),24000);assert.equal(bytes.readUInt16LE(22),1);assert.equal(bytes.readUInt32LE(40),bytes.length-44);assert.equal((bytes.length-44)%2,0,'Partial PCM sample in recording');const tail=(bytes.length-44)%960;if(tail)assert(bytes.subarray(bytes.length-tail).every(v=>v===0),'Finalized recording truncates non-silent audio');summary.audio_duration_ms=(bytes.length-44)/48;summary.frames_by_sender=[];for(const c of [call.a,call.b]){const seen=new Set();for(let pos=44;pos+960<=bytes.length;pos+=960){const chunk=bytes.subarray(pos,pos+960),seq=chunk.readInt16LE(c.lane*2)-1;if(seq===-1){for(let sample=c.lane;sample<480;sample+=2)assert.equal(chunk.readInt16LE(sample*2),0,'Corrupt silent recording lane');continue;}assert(seq>=0&&seq<frames,'Unexpected recording sequence');assert(!seen.has(seq),'Repeated recording interval');const expected=pcm(c.lane,c.tag,seq);for(let sample=c.lane;sample<480;sample+=2)assert.equal(chunk.readInt16LE(sample*2),expected.readInt16LE(sample*2),'Recorded audio mismatch');seen.add(seq);}summary.frames_by_sender.push(seen.size);assert.equal(seen.size,frames,'Missing input frames in finalized recording');}}catch(error){issue(`Recording ${call.ringid}: ${error.message}`);}}
}catch(error){issue(error.message);for(const call of calls)try{await call.a.request('calls.cut',{ringid:call.ringid});}catch{}}
finally{await stop();}
const first=resources[0],last=resources.at(-1);
const report={passed:errors.length===0,timestamp:new Date().toISOString(),mode:args.url?'remote':'local',scope:'PCM relay and local recording; provider network calls disabled in automatic local fixtures',server_binary:args.url?null:resolve(args.binary),host:{platform:platform(),arch:arch(),logical_cpus:cpus().length},calls:count,input_streams:count*2,requested_seconds:seconds,elapsed_seconds:Math.round(elapsed*100)/100,pcm:{sample_rate:24000,channels:1,frame_ms:20,sent_frames:sentFrames,received_frames:receivedFrames,expected_frames:count*2*frames,received_pcm_mib_per_second:elapsed?Math.round(receivedFrames*960/1048576/elapsed*1000)/1000:null,sent_websocket_bytes:sentWireBytes,received_websocket_bytes:receivedWireBytes},relay_latency_ms:{p50:quantile(latencies,.5),p95:quantile(latencies,.95),max:latencies.length?Math.round(latencies.reduce((a,b)=>Math.max(a,b),0)*100)/100:null},sender_lateness_ms:{p95:quantile(lateness,.95),max:lateness.length?Math.round(Math.max(...lateness)*100)/100:null},server_resources:resources.length?{pid,samples:resources.length,max_rss_mib:Math.round(Math.max(...resources.map(r=>r.rss_kib))/1024*100)/100,cpu_seconds:last.cpu_seconds-first.cpu_seconds,cpu_percent_of_one_core:Math.round((last.cpu_seconds-first.cpu_seconds)/(last.at-first.at)*100000*100)/100}:null,recordings,errors};
if(args.report)await writeFile(resolve(args.report),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
process.exitCode=report.passed?0:1;
