#!/usr/bin/env node
// End-to-end protocol checks use the real server and persistence, with isolated IAM fixtures.
import assert from 'node:assert/strict';
import {mkdtemp, writeFile, readFile, rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join, resolve} from 'node:path';
import {spawn} from 'node:child_process';
import {once} from 'node:events';

const directory=await mkdtemp(join(tmpdir(),'ring-contract-'));
const secret='isolated-ring-contract-app-secret';
const identities={alice:{actor:'c:alice',org_id:'test',display_name:'Alice',admin:true},bob:{actor:'c:bob',org_id:'test',display_name:'Bob'},eve:{actor:'c:eve',org_id:'other',display_name:'Eve'},si:{actor:'si:assistant',org_id:'test',display_name:'Assistant'},si2:{actor:'si:second',org_id:'test',display_name:'Second'},carol:{actor:'c:carol',org_id:'test',display_name:'Carol'}};
await writeFile(join(directory,'tokens.json'),JSON.stringify(identities));
let server, output='';
const clients=[];
const port=Number(process.env.RING_TEST_PORT||18765);
async function start(){server=spawn(resolve('target/debug/ring-server'),[],{env:{...process.env,RING_BIND:`127.0.0.1:${port}`,RING_DATA_DIR:directory,RING_TEST_APP_SECRET:secret,RING_TEST_TOKENS_FILE:join(directory,'tokens.json'),RING_DISABLE_PROVIDERS:'1',RING_TELEMETRY_ENABLED:'false'},stdio:['ignore','pipe','pipe']});server.stdout.on('data',c=>output+=c);server.stderr.on('data',c=>output+=c);for(let i=0;i<100;i++){try{if((await fetch(`http://127.0.0.1:${port}/health`)).ok)return;}catch{}await new Promise(r=>setTimeout(r,50));}throw new Error(`Server did not start: ${output}`);}
async function stop(){if(server?.exitCode===null){const closed=once(server,'exit');server.kill('SIGINT');await closed;}}
class Client{
 constructor(socket){this.socket=socket;this.pending=new Map();this.events=[];this.frames=[];socket.addEventListener('message',ev=>{const v=JSON.parse(ev.data);if(v.id&&this.pending.has(v.id)){const {resolve,reject,timer}=this.pending.get(v.id);clearTimeout(timer);this.pending.delete(v.id);v.ok?resolve(v.result):reject(Object.assign(new Error(v.error.message),v.error));}else{this.events.push(v);if(v.type==='media.audio')this.frames.push(v.data);}});}
 request(method,params={},id=crypto.randomUUID()){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(id);reject(new Error(`Timeout ${method}`))},8000);this.pending.set(id,{resolve,reject,timer});this.socket.send(JSON.stringify({id,method,params}));});}
 frame(type,data){this.socket.send(JSON.stringify({type,data}));}
 async ready(){await this.request('protocol.hello',{versions:[1],client:{name:'contract-tests',version:'0.1.0'},realm:'test',org_id:this.org||'test',test_app_secret:secret});}
 async login(token,org){this.org=org||identities[token]?.org_id||'test';await this.ready();this.session=await this.request('auth.login',{token});await this.request('events.subscribe',{});return this;}
 close(){this.socket.close();}
}
async function socket(){const ws=new WebSocket(`ws://127.0.0.1:${port}/ws`);await new Promise((res,rej)=>{ws.addEventListener('open',res,{once:true});ws.addEventListener('error',rej,{once:true});});const c=new Client(ws);clients.push(c);return c;}
async function login(token,org){return (await socket()).login(token,org);}
async function fails(fn,code){await assert.rejects(fn,e=>e.code===code,`expected ${code}`);}
const delay=ms=>new Promise(r=>setTimeout(r,ms));
let checks=0;
function checked(message){checks++;console.log(`ok ${checks} - ${message}`);}
try{
 await start();
 const unauth=await socket();await fails(()=>unauth.request('calls.list',{}),'HELLO_REQUIRED');await fails(()=>unauth.request('protocol.hello',{versions:[2]}),'PROTOCOL_UNSUPPORTED');await fails(()=>unauth.request('protocol.hello',{versions:[1],realm:'test',test_app_secret:'bad'}),'TEST_APP_AUTH_FAILED');checked('protocol negotiation and isolated test authentication');
 const a=await login('alice'),b=await login('bob'),eve=await login('eve'),si=await login('si'),si2=await login('si2'),carol=await login('carol');
 const call=await a.request('calls.init',{target:'@c:bob'},'first-call');assert.equal(call.state,'ringing');assert.equal((await a.request('calls.init',{target:'@c:bob'},'first-call')).ringid,call.ringid);await fails(()=>a.request('calls.init',{target:'c:carol'},'first-call'),'REQUEST_ID_REUSED');await fails(()=>eve.request('calls.get',{ringid:call.ringid}),'FORBIDDEN');checked('atomic call creation, exact retries, cross-org isolation');
 const b2=await login('bob');await b.request('calls.accept',{ringid:call.ringid});await fails(()=>b2.request('calls.accept',{ringid:call.ringid}),'INVITATION_UNAVAILABLE');const active=await a.request('calls.get',{ringid:call.ringid});assert.equal(active.state,'active');assert.equal(active.participants.length,2);checked('offer can be claimed by one device only');
 const ma=await a.request('media.attach',{ringid:call.ringid,device_id:a.session.device_id,purpose:'call'}),mb=await b.request('media.attach',{ringid:call.ringid,device_id:b.session.device_id,purpose:'call'});
 const positive=Buffer.alloc(960),negative=Buffer.alloc(960);for(let i=0;i<480;i++){positive.writeInt16LE(1000,i*2);negative.writeInt16LE(-200,i*2);}
 for(let seq=0;seq<15;seq++){a.frame('media.audio',{stream_id:ma.stream_id,seq,offset_ms:seq*20,audio_base64:positive.toString('base64')});b.frame('media.audio',{stream_id:mb.stream_id,seq,offset_ms:seq*20,audio_base64:negative.toString('base64')});await delay(20);}
 assert(a.frames.some(f=>Buffer.from(f.audio_base64,'base64').readInt16LE(0)===-200));assert(b.frames.some(f=>Buffer.from(f.audio_base64,'base64').readInt16LE(0)===1000));checked('real PCM relay mixes minus self, with independent output sequences');
 await fails(()=>b.request('calls.handoff',{ringid:call.ringid,to_device_id:b2.session.device_id}),'DEVICE_NOT_READY');const mb2=await b2.request('media.attach',{ringid:call.ringid,device_id:b2.session.device_id,purpose:'call'});assert.equal(mb2.state,'standby');let transcript=await b.request('transcript.list',{ringid:call.ringid});await b2.request('calls.handoff',{ringid:call.ringid,to_device_id:b2.session.device_id});assert.equal((await b.request('transcript.list',{ringid:call.ringid})).items.length,transcript.items.length);checked('handoff requires prepared owned device and does not alter conversation history');
 await a.request('calls.invite',{ringid:call.ringid,target:'c:carol'});await carol.request('calls.accept',{ringid:call.ringid});await a.request('calls.cut',{ringid:call.ringid});assert.equal((await b.request('calls.get',{ringid:call.ringid})).state,'active');await b.request('calls.cut',{ringid:call.ringid});assert.equal((await carol.request('calls.get',{ringid:call.ringid})).state,'ended');await delay(100);const recording=await b.request('recordings.get',{ringid:call.ringid});assert.equal(recording.status,'ready');assert(recording.audio_asset_id);await fails(()=>eve.request('assets.get',{asset_id:recording.audio_asset_id}),'FORBIDDEN');checked('group remains alive with two participants and finalizes full recording after final departure');
 await si.request('config.set',{scope:'actor',values:{'representative.default_context':'Assist with the launch.','representative.context_mode':'append'}});const prep=await si.request('calls.prepare',{action:'init',target:'c:alice',context:'Use concise replies.'});assert.equal(prep.approval_required,true);await fails(()=>si.request('calls.init',{target:'c:alice',preparation_id:prep.preparation_id}),'CONTEXT_APPROVAL_REQUIRED');await si.request('context.approve',{preparation_id:prep.preparation_id,valid_for_seconds:3600});const sc=await si.request('calls.init',{target:'c:alice',preparation_id:prep.preparation_id,start:'Hello'});await fails(()=>si.request('calls.init',{target:'c:bob'}),'SILICON_BUSY');await a.request('calls.accept',{ringid:sc.ringid});await fails(()=>si.request('calls.handoff',{ringid:sc.ringid,to_device_id:a.session.device_id}),'DEVICE_NOT_READY');checked('reviewed context approval and single-call silicon reservation');
 const busy=await b.request('calls.init',{target:'si:assistant'});assert.equal(busy.state,'voicemail');const vm=await b.request('voicemail.begin',{ringid:busy.ringid,format:'audio'});const vstream=await b.request('media.attach',{ringid:busy.ringid,device_id:b.session.device_id,purpose:'voicemail',voicemail_id:vm.voicemail_id});b.frame('media.audio',{stream_id:vstream.stream_id,seq:0,offset_ms:0,audio_base64:positive.toString('base64')});b.frame('media.audio',{stream_id:vstream.stream_id,seq:2,offset_ms:40,audio_base64:positive.toString('base64')});await delay(100);assert.equal((await b.request('media.detach',{stream_id:vstream.stream_id,last_seq:2})).complete,false);await fails(()=>b.request('voicemail.commit',{voicemail_id:vm.voicemail_id}),'AUDIO_NOT_READY');await b.request('voicemail.abort',{voicemail_id:vm.voicemail_id});checked('busy voicemail is private and missing chunks cannot be committed');
 const vm2=await b.request('voicemail.begin',{ringid:busy.ringid,format:'audio'});const vstream2=await b.request('media.attach',{ringid:busy.ringid,device_id:b.session.device_id,purpose:'voicemail',voicemail_id:vm2.voicemail_id});for(let seq=0;seq<3;seq++)b.frame('media.audio',{stream_id:vstream2.stream_id,seq,offset_ms:seq*20,audio_base64:positive.toString('base64')});await delay(50);assert.equal((await b.request('media.detach',{stream_id:vstream2.stream_id,last_seq:2})).complete,true);await b.request('voicemail.commit',{voicemail_id:vm2.voicemail_id});assert((await si.request('voicemail.list',{})).items.some(v=>v.voicemail_id===vm2.voicemail_id));assert.equal((await si.request('voicemail.get',{voicemail_id:vm2.voicemail_id})).read,false);await si.request('voicemail.mark',{voicemail_id:vm2.voicemail_id,read:true});assert(!(await si.request('voicemail.list',{})).items.some(v=>v.voicemail_id===vm2.voicemail_id));await fails(()=>a.request('voicemail.get',{voicemail_id:vm2.voicemail_id}),'FORBIDDEN');checked('complete voicemail delivery, explicit read state, recipient access');
 await fails(()=>si.request('representative.send',{ringid:sc.ringid,kind:'commentary',text:'🙂'.repeat(161),delegation_id:null}),'INVALID_INPUT');await si.request('representative.send',{ringid:sc.ringid,kind:'thinking',text:'Checking the launch.',delegation_id:null});assert(!(await a.request('transcript.list',{ringid:sc.ringid})).items.some(e=>e.kind==='thinking'));assert((await si.request('transcript.list',{ringid:sc.ringid})).items.some(e=>e.kind==='thinking'));await si.request('calls.cut',{ringid:sc.ringid});checked('Unicode boundaries and private thinking visibility');
 await si.request('config.set',{scope:'actor',values:{'representative.default_context':'New instructions.'}});await fails(()=>si.request('calls.init',{target:'c:alice',preparation_id:prep.preparation_id}),'CONTEXT_CHANGED');await fails(()=>si.request('calls.prepare',{action:'init',target:'c:alice',context:'🙂'.repeat(401)}),'INVALID_INPUT');checked('edited defaults invalidate approvals without truncating text');
 const declined=await a.request('calls.init',{target:'si:second'});await fails(()=>si2.request('calls.decline',{ringid:declined.ringid}),'INVALID_INPUT');await si2.request('calls.decline',{ringid:declined.ringid,give_no_reason:true});assert.equal((await a.request('calls.get',{ringid:declined.ringid})).state,'voicemail');checked('silicon decline requires reason or explicit opt-out');
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5K0AAAAASUVORK5CYII=','base64');const photo=await a.request('assets.begin',{purpose:'profile_photo',mime_type:'image/png',size_bytes:png.length});a.frame('assets.chunk',{asset_id:photo.asset_id,seq:0,data_base64:png.toString('base64')});await delay(50);await a.request('assets.complete',{asset_id:photo.asset_id});await fails(()=>b.request('profile.update',{photo_asset_id:photo.asset_id}),'FORBIDDEN');checked('asset uploads enforce ownership and completeness');
 const resumed=await socket();await resumed.ready();await resumed.request('auth.resume',{session_token:a.session.session_token,device_id:a.session.device_id});await a.request('devices.revoke',{device_id:a.session.device_id});await fails(()=>resumed.request('calls.list',{}),'AUTH_REQUIRED');checked('device revocation immediately invalidates session access');
 for(const c of clients)c.close();await delay(100);await stop();await start();const restored=await login('si');assert((await restored.request('voicemail.list',{unread:false})).items.some(v=>v.voicemail_id===vm2.voicemail_id));const hist=await restored.request('calls.get',{ringid:sc.ringid});assert.equal(hist.state,'ended');checked('call history and voicemail survive a server restart');
 console.log(`PASS: ${checks} end-to-end checks`);
}finally{for(const c of clients)c.close();await delay(30);await stop();await rm(directory,{recursive:true,force:true});}
